# Generated by Django 5.2.17 on 2026-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ROCKS ELECTRIC', max_length=120)),
                ('phone', models.CharField(default='0100 000 0000', max_length=30)),
                ('whatsapp', models.CharField(default='201000000000', max_length=30)),
                ('email', models.EmailField(default='hello@rocks-electric.com', max_length=254)),
                ('address', models.CharField(default='القاهرة، مصر', max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='حلول كهربائية مختارة لتدوم.', max_length=255)),
                ('shipping_message', models.CharField(default='شحن سريع لكل محافظات مصر', max_length=160)),
                ('currency', models.CharField(default='ج.م', max_length=12)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
