# Generated by Django 5.2.17 on 2026-09-01 05:47

from django.db import migrations, models


def clear_known_placeholders(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(phone="0100 000 0000").update(phone="")
    SiteSettings.objects.filter(whatsapp="201000000000").update(whatsapp="")
    SiteSettings.objects.filter(email="hello@rocks-electric.com").update(email="")
    SiteSettings.objects.filter(address="القاهرة، مصر").update(address="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repair_missing_core_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_instructions',
            field=models.TextField(blank=True, help_text='تظهر فقط عند تفعيل التحويل البنكي في صفحة الدفع.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(clear_known_placeholders, migrations.RunPython.noop),
    ]
