# Generated by Django 5.2.17 on 2026-09-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_bank_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='bank_instructions',
        ),
    ]
