# Generated by Django 5.2.17 on 2026-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitesettings_bank_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='EGP', max_length=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='Powering a cleaner tomorrow.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shipping_message',
            field=models.CharField(default='Fast delivery across Egypt', max_length=160),
        ),
    ]
