# Generated by Django 5.2.17 on 2026-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='banners/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(choices=[('hero', 'الرئيسية'), ('offer', 'عرض'), ('promo', 'ترويجي')], default='promo', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
