# Generated by Django 5.2.17 on 2026-09-01 05:54

import catalog.validators
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/', validators=[catalog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=255, validators=[marketing.models.validate_banner_link]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='banners/', validators=[catalog.validators.validate_image_size]),
        ),
    ]
