# Generated by Django 5.2.17 on 2026-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_banner_image_alter_banner_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.CharField(choices=[('hero', 'Home hero'), ('offer', 'Offer'), ('promo', 'Promotional')], default='promo', max_length=20),
        ),
    ]
