# Generated by Django 5.2.17 on 2026-09-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productvariant_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'name'), 'verbose_name_plural': 'Categories'},
        ),
    ]
