# Generated by Django 5.2.12 on 2026-10-03 11:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_seo_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_price_positive',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_old_price_valid',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gt', 0), _connector='OR'), name='product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('old_price__isnull', True), models.Q(('price__isnull', False), ('old_price__gte', models.F('price'))), _connector='OR'), name='product_old_price_valid'),
        ),
    ]
