# Generated by Django 5.2.17 on 2026-09-01 05:47

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


def populate_checkout_tokens(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.filter(checkout_token__isnull=True).iterator():
        order.checkout_token = uuid.uuid4()
        order.save(update_fields=("checkout_token",))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_image_alter_product_main_image_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_checkout_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('pending', 'قيد المراجعة'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order__gte', 0)), name='coupon_minimum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='coupon_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type', 'fixed'), ('value__lte', 100), _connector='OR'), name='coupon_percentage_max_100'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='order_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_item_total_nonnegative'),
        ),
    ]
