# Generated by Django 5.2.17 on 2026-09-02 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


GOVERNORATES = (
    "القاهرة", "الجيزة", "الإسكندرية", "الدقهلية", "البحر الأحمر", "البحيرة",
    "الفيوم", "الغربية", "الإسماعيلية", "المنوفية", "المنيا", "القليوبية",
    "الوادي الجديد", "السويس", "أسوان", "أسيوط", "بني سويف", "بورسعيد",
    "دمياط", "الشرقية", "جنوب سيناء", "كفر الشيخ", "مطروح", "الأقصر",
    "قنا", "شمال سيناء", "سوهاج",
)


def prepare_cod_and_shipping_zones(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    ShippingZone = apps.get_model("orders", "ShippingZone")
    Order.objects.exclude(payment_method="cod").update(payment_method="cod", payment_status="unpaid")
    ShippingZone.objects.bulk_create([
        ShippingZone(name=name, shipping_cost=Decimal("75.00"), free_shipping_threshold=Decimal("1500.00"), sort_order=index)
        for index, name in enumerate(GOVERNORATES)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productvariant_price_and_more'),
        ('orders', '0002_order_checkout_token_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'الدفع عند الاستلام')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('skipped', 'لا يوجد مستلمون')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='shipping_zone_cost_nonnegative'), models.CheckConstraint(condition=models.Q(('free_shipping_threshold__isnull', True), ('free_shipping_threshold__gte', 0), _connector='OR'), name='shipping_zone_threshold_nonnegative')],
            },
        ),
        migrations.RunPython(prepare_cod_and_shipping_zones, migrations.RunPython.noop),
    ]
