# Generated by Django 5.2.17 on 2026-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_order_payment_method_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الإرسال'), ('sending', 'جارٍ الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('skipped', 'لا يوجد مستلمون')], db_index=True, default='pending', max_length=20),
        ),
    ]
